# Generated by Django 6.1.1 on 2026-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Store Manager'), ('STAFF', 'Staff / Cashier')], default='STAFF', max_length=10),
        ),
    ]
